### ISSUE TITLE
download information and its specification

### ISSUE THREAD

**Issue by bochengyang** [hofitness/ho.fitness#3]
# 下載資訊

iOS 下載連結  https://apps.apple.com/us/app/ho-fitness/id6446753120
Android 下載連結 https://play.google.com/store/apps/details?id=com.ho.fitness.app.flutter

如果只有一個按鈕的想要用 react + nextjs 去判斷

ChatGPT 4.0 咒語 `can I use frontend code like react and nextjs to determine which ios or android is browsering my page, and when user click download link, we will guide them to corresponding app store or google play`

**Comment by chnbohwr** [comment]
has added https://github.com/hofitness/ho.fitness/commit/ba7d5cedb6de00a66afca71d90cf963ed7e58c74
