### ISSUE TITLE
Header style change

### ISSUE THREAD

**Issue by bochengyang** [hofitness/ho.fitness#4]
我們會想要在首頁還未滾動時 依然呈現原本的樣式

而開始往下滾動時 則改以下圖方式呈現，並維持在最上緣 (目前已經是了)

![image](https://user-images.githubusercontent.com/8037872/233752372-2e429c0d-398e-4366-80cd-a59574ec850b.png)

**Comment by chnbohwr** [comment]
change header style https://github.com/hofitness/ho.fitness/commit/ba7d5cedb6de00a66afca71d90cf963ed7e58c74

**Comment by bochengyang** [comment]
issue closed due to complete
