### ISSUE TITLE
Footer information

### ISSUE THREAD

**Issue by bochengyang** [hofitness/ho.fitness#5]
# Footer 資訊

LINE: https://lin.ee/TcyW7td
Facebook: https://www.facebook.com/HOFITNESS
Instagram: https://www.instagram.com/HOFITNESS

**Comment by chnbohwr** [comment]
add information   https://github.com/hofitness/ho.fitness/commit/ba7d5cedb6de00a66afca71d90cf963ed7e58c74

**Comment by bochengyang** [comment]
NOTE: The Instagram might change to @HOFITNESS, but let's keep it now.

issue closed due to complete
