### ISSUE TITLE
The background in the first section not change when width is 1024

### ISSUE THREAD

**Issue by bochengyang** [hofitness/ho.fitness#6]
Original design

![image](https://user-images.githubusercontent.com/8037872/233752795-db0f0807-f3b3-4199-89da-9f3810b42c3b.png)

Current

![image](https://user-images.githubusercontent.com/8037872/233752807-b2ee3f10-881b-4d3b-98de-096e5c35c185.png)

**Comment by chnbohwr** [comment]
I have tried my best to adjust the position of the letter "H" in the background to the center of the screen. However, considering that the width of the girl's PNG needs to be calculated with the background curve, the background may not be exactly the same as the design. Therefore, I need you to review and see if further adjustments are needed.

**Comment by bochengyang** [comment]
You have done an amazing job!

issue closed due to complete
