### ISSUE TITLE
only display the tab `免費體驗` on the right hand side when start scrolling

### ISSUE THREAD

**Issue by bochengyang** [hofitness/ho.fitness#7]
We would like to remove the tab button when we are in the first section without scrolling, only show the button `免費體驗` when the user starts scrolling on the right-hand side of the screen

Current screen,

![image](https://user-images.githubusercontent.com/8037872/233753103-3086f883-a29e-46db-97aa-073bd1bad081.png)

**Comment by chnbohwr** [comment]
add btn and rules https://github.com/hofitness/ho.fitness/commit/ba7d5cedb6de00a66afca71d90cf963ed7e58c74

**Comment by bochengyang** [comment]
issue closed due to complete
