### ISSUE TITLE
Google Analytic 4.0

### ISSUE THREAD

**Issue by bochengyang** [hofitness/ho.fitness#9]
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-9VT1H8YDM0"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-9VT1H8YDM0');
</script>
```

**Comment by bochengyang** [comment]
it's not working, it might be the this [line](https://github.com/hofitness/ho.fitness/blob/feature/layout/app/page.tsx#L12) should change to [react-ga4](url) instead, do you mind help me to change this?

**Comment by chnbohwr** [comment]
I apologize for seeing this issue so late. I have switched to using react-ga4. Please give it a try and see if it works.

**Comment by bochengyang** [comment]
it works 👍
